feat: .github/workflows/python-ci.yaml

diff --git a/.github/workflows/python-ci.yaml b/.github/workflows/python-ci.yaml
--- a/.github/workflows/python-ci.yaml
+++ b/.github/workflows/python-ci.yaml
@@ -78,7 +78,7 @@ jobs:
         run: sleep 10
       - name: smoke test
         run: |
-          curl -f http://localhost:5000/health || (echo "Smoke test failed" && exit 1)
+          curl -f http://localhost:5000/api/health || (echo "Smoke test failed" && exit 1)
           curl -f http://localhost:5000 || (echo "Smoke test failed" && exit 1)
       - name: Show container logs on failure
         if: failure()
